"""your message

Revision ID: d299c4ead72d
Revises: 2d92b6a7863b
Create Date: 2024-07-27 10:25:25.652953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd299c4ead72d'
down_revision = '2d92b6a7863b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###